project_name: meteor

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - make clean

builds:
  - main: ./main.go
    id: "linux"
    binary: meteor
    flags: [-a]
    ldflags:
      - -X github.com/goto/meteor/cmd.Version={{.Tag}}
      - -X github.com/goto/meteor/cmd.BuildCommit={{.FullCommit}}
      - -X github.com/goto/meteor/cmd.BuildDate={{.Date}}
    goos: [linux]
    goarch: [amd64, arm64] # skip goarch 386 and arm due to conflicts with "github.com/blastrain/vitess-sqlparser" library
    env:
      - CGO_ENABLED=0
  - main: ./main.go
    id: "darwin"
    binary: meteor
    flags: [-a]
    ldflags:
      - -X github.com/goto/meteor/cmd.Version={{.Tag}}
      - -X github.com/goto/meteor/cmd.BuildCommit={{.FullCommit}}
      - -X github.com/goto/meteor/cmd.BuildDate={{.Date}}
    goos: [darwin]
    goarch: [amd64, 386, arm, arm64]
    env:
      - CGO_ENABLED=0
  - main: ./main.go
    id: "windows"
    binary: meteor
    flags: [-a]
    ldflags:
      - -X github.com/goto/meteor/cmd.Version={{.Tag}}
      - -X github.com/goto/meteor/cmd.BuildCommit={{.FullCommit}}
      - -X github.com/goto/meteor/cmd.BuildDate={{.Date}}
    goos: [windows]
    goarch: [amd64, arm64] # skip goarch 386 and arm due to conflicts with "github.com/blastrain/vitess-sqlparser" library
    env:
      - CGO_ENABLED=0

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "darwin" }}macos
      {{- else if eq .Arch "linux" }}linux
      {{- else if eq .Arch "windows" }}windows
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - linux
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/gotocompany/{{.ProjectName}}:latest"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}-amd64"

brews:
  - name: meteor
    homepage: "https://github.com/goto/meteor"
    description: "Metadata collection tool."
    tap:
      owner: goto
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula

    dependencies:
      - name: git
    install: |-
      bin.install "meteor"
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
